### PR TITLE
Update org.onlyoffice.desktopeditors.json

### PR DESCRIPTION
**Pull request by alexpattyn**
Updated Onlyoffice to 5.5.1, to match upstream.

### CODE REVIEW

**Comment by alexpattyn** [comment]
Seems https://raw.githubusercontent.com/ONLYOFFICE/desktop-apps/master/win-linux/package/linux/common/onlyoffice/usr/share/applications/desktopeditors.desktop is 404

**Comment by alexpattyn** [comment]
Seems most of the raw.github.com/... links are broken. So I'll have get new links for those.

**Comment by agolybev** [comment]
Updated to 5.5.1 in https://github.com/flathub/org.onlyoffice.desktopeditors/pull/11

**Comment by alexpattyn** [comment]
Thanks!

**Pull request closed without merging**
