### PR TITLE
Update version to 6.4.2

### PR DESCRIPTION
**Pull request by romandemidov**

### CODE REVIEW

**Comment by janxkoci** [comment]
Is there any problem with this update? Debian and other packages are available for weeks now.

**Comment by ShockwaveNN** [comment]
@janxkoci There was several small problems, but we usually release all other versions of DesktopEdtiros sometime later after the main release of deb and rpm, mostly because `snap`, `flatpak` and `AppImage` support a whole myriad of systems and we need to check majority of them

So we working as hard as we can to release those version, but cannot guarantee any time frame except `soon`

**Comment by janxkoci** [comment]
Oh, that's the opposite of what I would expect. I thought flatpak and snap are designed to work everywhere the same, so you could test it on just one or a few systems and expect it to work on all (or most). Isn't consistency what these formats were aiming for? Or is the reality  so very different from this expectation?

**Comment by ShockwaveNN** [comment]
> Or is the reality so very different from this expectation?

Yes, a lot of issues arise in different desktop environments and different system libraries (like libc) versions

So having flatpak is simpler than for example making distributive specific targets, but it's not solving ALL ISSUES

**Comment by janxkoci** [comment]
The update just arrived and it's _awesome!_

**Pull request merged**
